name: Go

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.6

      - name: Check
        run: go generate ./example/... && if [[ $(git diff) ]] ; then echo "you need to run go generate" ; git diff ; exit 1 ; fi

      - name: Test
        run: go test -bench=. -benchmem -v ./example/...

      - name: Test Race
        run: go test -bench=. -benchmem -v ./example/... -race
