name: Go

on:
  push:
    tags-ignore:
      - 'v*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Test
        run: go test ./...

      - name: Test Race
        run: go test -race ./...
